const KEY='becomingMeData', todayKey=dateKey(new Date());
const habits=[['coding','💻','Coding','Practice for at least 20 minutes'],['dsa','🧠','DSA','Solve at least 1 problem'],['exercise','🧘','Exercise / Yoga','Move for 10–15 minutes'],['college','📚','College','Complete important college work'],['career','💼','Career / Project','Work on a CSE skill/project'],['sleep','🌙','Sleep','Maintain a healthy sleep routine'],['creative','🎨','Personal / Creative','Do something for yourself']];
const personal=[['exercise','🏃','Exercise'],['yoga','🧘','Yoga'],['reading','📖','Reading'],['sketching','✏️','Sketching / Creativity'],['sleep','🌙','Sleep'],['family','🏡','Family time'],['personal','☕','Personal time']];
const techs=['HTML','CSS','JavaScript','Node.js','Express.js','SQL','Git/GitHub'];
const placement=['Resume','LinkedIn','GitHub','Aptitude','Mock interviews','Technical interview preparation','Internship applications'];
const messages=["You don't need to do everything today.",'Small steps become big changes.','Consistency beats intensity.','You showed up. That matters.',"Progress doesn't have to be dramatic.",'Future you will thank you.','One day at a time.','You are building your future slowly.'];
const defaultSkills={Programming:40,DSA:25,'Web Development':30,SQL:20,'Git/GitHub':15};
function defaults(){return{name:'You',theme:'light',habits:{},habitHistory:{},personalHabits:{},skills:{...defaultSkills},programming:{},dsa:{},tech:{},placement:{},projects:[],journal:{},motivation:{}}}
function loadData(){try{return Object.assign(defaults(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return defaults()}}
let data=loadData(),toastTimer;
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function dateKey(d){return d.toISOString().slice(0,10)} function dateText(d){return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(d)} function esc(v){const x=document.createElement('div');x.textContent=v||'';return x.innerHTML}
function toast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderDate(){const d=dateText(new Date());document.getElementById('currentDate').textContent=d;document.getElementById('welcomeDate').textContent=d;document.getElementById('datePill').textContent=d.split(',')[0]+', '+d.split(',')[1];document.getElementById('journalDateLabel').textContent=d}
function renderHome(){const day=data.habits[todayKey]||{};document.getElementById('habitList').innerHTML=habits.map(h=>`<article class="habit-card ${day[h[0]]?'completed':''}"><div class="habit-top"><span class="habit-icon">${h[1]}</span><button class="check-button" data-habit="${h[0]}" aria-label="Mark ${h[2]} complete">${day[h[0]]?'✓':''}</button></div><div><h3>${h[2]}</h3><p>${h[3]}</p></div></article>`).join('');document.querySelectorAll('[data-habit]').forEach(b=>b.onclick=()=>toggleHabit(b.dataset.habit));updateProgress();updateStreak();weekly()}
function toggleHabit(id){data.habits[todayKey]??={};data.habits[todayKey][id]=!data.habits[todayKey][id];if(Object.values(data.habits[todayKey]).some(Boolean))data.habitHistory[todayKey]=true;save();renderHome();toast(data.habits[todayKey][id]?'A small win for today ✦':'Progress can be gentle.')}
function updateProgress(){const count=habits.filter(h=>(data.habits[todayKey]||{})[h[0]]).length;document.getElementById('progressNumber').textContent=`${count} / 7`;document.getElementById('todayProgressBar').style.width=`${count/7*100}%`;document.getElementById('supportMessage').textContent=count===7?'You showed up today. Proud of you. 💚':['Showing up is already a win.','Small progress still counts 🌱',"You're showing up.",'One step closer.','Keep going.'][Math.min(count,4)]}
function updateStreak(){let n=0,d=new Date();while(data.habitHistory[dateKey(d)]){n++;d.setDate(d.getDate()-1)}document.getElementById('streakCount').textContent=n}
function startWeek(d){const x=new Date(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));x.setHours(0,0,0,0);return x}
function weekly(){const start=startWeek(new Date()),days=[],shown=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),yes=!!data.habitHistory[key];days.push(`<div class="week-day ${yes?'showed':''} ${key===todayKey?'today':''}"><span>${d.toLocaleDateString('en-US',{weekday:'short'})}</span><strong>${yes?'✓':'○'}</strong></div>`);if(yes)shown.push(key)}document.getElementById('weekDays').innerHTML=days.join('');document.getElementById('weeklyCount').textContent=`${shown.length} / 7 days`;document.getElementById('weeklyProgressBar').style.width=`${shown.length/7*100}%`}
function renderSkills(){document.getElementById('skillsList').innerHTML=Object.entries(data.skills).map(([name,val])=>`<div class="skill-row"><span class="skill-label">${name}</span><label class="skill-control"><input type="range" min="0" max="100" value="${val}" data-skill="${name}" aria-label="${name} progress"></label><span class="skill-value" id="skill-${name.replace(/[^a-z]/gi,'')}">${val}%</span></div>`).join('');document.querySelectorAll('[data-skill]').forEach(i=>i.oninput=()=>{data.skills[i.dataset.skill]=+i.value;document.getElementById(`skill-${i.dataset.skill.replace(/[^a-z]/gi,'')}`).textContent=`${i.value}%`;save()})}
function renderCse(){const p=data.programming,d=data.dsa;languageInput.value=p.language||'';topicsInput.value=p.topics||'';practiceDaysInput.value=p.practiceDays||'';problemsSolved.value=d.problemsSolved||'';easyProblems.value=d.easy||'';mediumProblems.value=d.medium||'';hardProblems.value=d.hard||'';currentTopic.value=d.topic||'';techList.innerHTML=techs.map(n=>`<div class="tech-item"><strong>${n}</strong><select class="status-select" data-tech="${n}"><option ${!data.tech[n]||data.tech[n]==='Not Started'?'selected':''}>Not Started</option><option ${data.tech[n]==='Learning'?'selected':''}>Learning</option><option ${data.tech[n]==='Comfortable'?'selected':''}>Comfortable</option></select></div>`).join('');document.querySelectorAll('[data-tech]').forEach(s=>s.onchange=()=>{data.tech[s.dataset.tech]=s.value;save();toast(`${s.dataset.tech} updated`)});placementList.innerHTML=placement.map(n=>`<label class="check-row ${data.placement[n]?'done':''}"><input type="checkbox" data-placement="${n}" ${data.placement[n]?'checked':''}>${n}</label>`).join('');document.querySelectorAll('[data-placement]').forEach(i=>i.onchange=()=>{data.placement[i.dataset.placement]=i.checked;save();renderCse()});renderProjects();snapshots()}
function saveProgramming(){data.programming={language:languageInput.value,topics:topicsInput.value,practiceDays:+practiceDaysInput.value||0};save();snapshots();toast('Programming progress saved ✦')}
function saveDsa(){data.dsa={problemsSolved:+problemsSolved.value||0,easy:+easyProblems.value||0,medium:+mediumProblems.value||0,hard:+hardProblems.value||0,topic:currentTopic.value};save();snapshots();toast('DSA progress saved ✦')}
function snapshots(){snapshotProblems.textContent=data.dsa.problemsSolved||0;snapshotPractice.textContent=data.programming.practiceDays||0;snapshotProjects.textContent=data.projects.length;personalSnapshot.textContent=`${Object.values(data.personalHabits[todayKey]||{}).filter(Boolean).length} / 7`}
function renderProjects(){projectList.innerHTML=data.projects.length?data.projects.map(p=>`<article class="project-card"><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="project-meta"><span>${esc(p.status)}</span><span>${esc(p.technologies||'No technologies yet')}</span>${p.link?`<a href="${esc(p.link)}" target="_blank" rel="noopener">GitHub ↗</a>`:''}</div></article>`).join(''):'<div class="empty-state">Your first project can be small. A page, a script, a question answered.</div>'}
function renderPersonal(){const day=data.personalHabits[todayKey]||{};personalHabitList.innerHTML=personal.map(h=>`<label class="personal-habit ${day[h[0]]?'done':''}"><input type="checkbox" data-personal="${h[0]}" ${day[h[0]]?'checked':''}><span>${h[1]} ${h[2]}</span></label>`).join('');document.querySelectorAll('[data-personal]').forEach(i=>i.onchange=()=>{data.personalHabits[todayKey]??={};data.personalHabits[todayKey][i.dataset.personal]=i.checked;save();renderPersonal()});journalInput.value=data.journal[todayKey]||'';renderJournal();snapshots()}
function renderJournal(){const entries=Object.entries(data.journal).filter(([,v])=>v).sort(([a],[b])=>b.localeCompare(a));journalHistory.innerHTML=entries.length?entries.map(([d,n])=>`<article class="history-note"><strong>${dateText(new Date(`${d}T12:00:00`))}</strong><p>${esc(n)}</p></article>`).join(''):'<div class="empty-state">Your thoughts from today and the days ahead will gather here.</div>'}
function theme(mode){data.theme=mode;document.documentElement.dataset.theme=mode;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===mode));save()}
function renderSettings(){nameInput.value=data.name==='You'?'':data.name;sidebarName.textContent=data.name;sidebarInitial.textContent=data.name[0].toUpperCase();footerName.textContent=data.name;theme(data.theme||'light')}
function section(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.section===id));document.querySelector('.sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
function resetToday(){delete data.habits[todayKey];delete data.personalHabits[todayKey];save();renderHome();renderPersonal();toast('Today is ready for a fresh start.')}
function render(){renderDate();const saved=data.motivation[todayKey]||(data.motivation[todayKey]=messages[Math.floor(Math.random()*messages.length)]);dailyMotivation.textContent=saved;save();renderHome();renderSkills();renderCse();renderPersonal();renderSettings()}
document.querySelectorAll('[data-section]').forEach(a=>a.onclick=e=>{e.preventDefault();section(a.dataset.section);history.replaceState(null,'',`#${a.dataset.section}`)});mobileMenu.onclick=()=>document.querySelector('.sidebar').classList.toggle('open');quickTheme.onclick=()=>theme(data.theme==='dark'?'light':'dark');saveProgramming.onclick=saveProgramming;saveDsa.onclick=saveDsa;saveJournal.onclick=()=>{data.journal[todayKey]=journalInput.value.trim();save();renderJournal();toast('Note saved for today ✦')};saveName.onclick=()=>{data.name=nameInput.value.trim()||'You';save();renderSettings();toast(`Hello, ${data.name} ✦`)};document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>theme(b.dataset.themeChoice));resetToday.onclick=resetToday;resetAll.onclick=()=>{if(confirm('Reset all Becoming Me data? This cannot be undone.')){data=defaults();save();render();toast('Everything is ready for a new beginning.')}};openProjectModal.onclick=()=>{projectModal.classList.add('open');projectModal.setAttribute('aria-hidden','false')};closeProjectModal.onclick=()=>{projectModal.classList.remove('open');projectModal.setAttribute('aria-hidden','true')};projectModal.onclick=e=>{if(e.target===projectModal)closeProjectModal.onclick()};projectForm.onsubmit=e=>{e.preventDefault();const f=new FormData(projectForm);data.projects.unshift(Object.fromEntries(f));save();renderProjects();snapshots();closeProjectModal.onclick();projectForm.reset();toast('Project added to your journey ✦')};onkeydown=e=>{if(e.key==='Escape')closeProjectModal.onclick()};render();const hash=location.hash.slice(1);if(['home','progress','cse','personal','settings'].includes(hash))section(hash);